### PR TITLE
03: stirling's approximation

### PR DESCRIPTION
**Pull request by ayazhafiz**
Stirling's Approximation of factorials for Week 03, per #6.

@luke-bhan how does this look to you?

### CODE REVIEW

**Comment by luke-bhan** [comment]
It's beautiful

**Comment by luke-bhan** [comment]
And then if we really wanna expand and go far. We can use string numbers into an array or something similar and then have them write a sterling function that iterates through that in the future. But, that also might be a trivial task and unnecessary to add.

**Comment by ayazhafiz** [comment]
I like that. I think it would be cool to expand the BigNum exercise, and then have an exercise evaluating factorials of huge numbers.

In fact, I tried this out last night, and it requires subtraction, multiplication, and conditional operators on the BigNum class, which I think may be doable for most, albeit time consuming.

**Comment by luke-bhan** [comment]
If you wanna go that direction I like it, but also think we’re assuming people are doing the code each week for it otherwise it’s be a long problem if someone just starts week 5 and gets a build on something others already have most of the design for.

**Comment by ayazhafiz** [comment]
Yep, that is true. What do you think about offering two options for the week 04 then - this "harder" version that serves as a culmination of the first three weeks, and another one that's a pivot to some other topic?

**Comment by luke-bhan** [comment]
I think thatd be great if you have the time to do the work

**Comment by ayazhafiz** [comment]
Merged in ba41d69adbc4c505db6e8ea2adcd4f0bbb8f02f8.

**Pull request closed without merging**
